services:

  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=dbname
    tmpfs:
      - /var/lib/postgresql/data
    #command: ["postgres", "-c", "log_statement=all"]
