services:

  postgres:
    image: registry.gitlab.com/filipelbc/svelte-postgraphile-boilerplate/postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=app_owner_password
      - POSTGRES_USER=app_owner
      - POSTGRES_DB=app
    tmpfs:
      - /var/lib/postgresql/data
    #command: ["postgres", "-c", "log_statement=all"]
